name: Deploy
on:
  push:
    branches: [main] # or whatever your default branch is

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20" # or whatever version you're using

      - name: Install Dependencies
        run: npm install --force

      - name: Build
        run: npm run build
